version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-184-73-169-151.compute-1.amazonaws.com
            port: '5432'
            database: dd2trsfl3dtg26
            ssl: true
            user: xezmwobvphtteq
            password: 44c60765f7de2cff3866daced59c8ba2b80badf531017cff155db0cd2265c69c
            migrations: true